//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeachGuide.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeachGuide.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUscolumn {
            get {
                return ResourceManager.GetString("AboutUscolumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulf Shores, Alabama.
        /// </summary>
        public static string Albamaheading {
            get {
                return ResourceManager.GetString("Albamaheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Arealabel {
            get {
                return ResourceManager.GetString("Arealabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Bathrooms.
        /// </summary>
        public static string Bathroominfo {
            get {
                return ResourceManager.GetString("Bathroominfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach a Buzz.
        /// </summary>
        public static string BeachABuzzName {
            get {
                return ResourceManager.GetString("BeachABuzzName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach Buzz.
        /// </summary>
        public static string BeachBuzzCol {
            get {
                return ResourceManager.GetString("BeachBuzzCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeachGuide Magazine.
        /// </summary>
        public static string BeachGuideMagazinCol {
            get {
                return ResourceManager.GetString("BeachGuideMagazinCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Bedroom.
        /// </summary>
        public static string Bedroomcount {
            get {
                return ResourceManager.GetString("Bedroomcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destin’s beautiful holiday isle is the setting for aegean, a....
        /// </summary>
        public static string cardtextdetails {
            get {
                return ResourceManager.GetString("cardtextdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string Checkinlabel {
            get {
                return ResourceManager.GetString("Checkinlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckoutLabel {
            get {
                return ResourceManager.GetString("CheckoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with BeachGuide.
        /// </summary>
        public static string ConnectBeachGuideCol {
            get {
                return ResourceManager.GetString("ConnectBeachGuideCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact BeachGuide.
        /// </summary>
        public static string ContactBeachCol {
            get {
                return ResourceManager.GetString("ContactBeachCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        public static string DealsColumn {
            get {
                return ResourceManager.GetString("DealsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        public static string DinnerInfo {
            get {
                return ResourceManager.GetString("DinnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Eventsinfo {
            get {
                return ResourceManager.GetString("Eventsinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackColumn {
            get {
                return ResourceManager.GetString("FeedbackColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing.
        /// </summary>
        public static string Fishinginfo {
            get {
                return ResourceManager.GetString("Fishinginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find beachfront vacation rentals along the beautiful white-sand beaches of the Alabama and Florida Gulf Coast.
        ///                            Choose from condo rentals, cottages, vacation homes and hotels. Learn more about things to do in our beach destinations, and find information on dining, shopping, golf, fishing and attractions. Also be sure to join us on Facebook and Pinterest,
        ///                            and join our email list to make sure you always get the latest news about events and special deals [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FooterInformation {
            get {
                return ResourceManager.GetString("FooterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        public static string GolfDetails {
            get {
                return ResourceManager.GetString("GolfDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        public static string Golfinfo {
            get {
                return ResourceManager.GetString("Golfinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string GuestLabel {
            get {
                return ResourceManager.GetString("GuestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulf Shores, Alabama.
        /// </summary>
        public static string GulfAlabamaHeading {
            get {
                return ResourceManager.GetString("GulfAlabamaHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string GymInfo {
            get {
                return ResourceManager.GetString("GymInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeColumn {
            get {
                return ResourceManager.GetString("HomeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string InformationNavslide {
            get {
                return ResourceManager.GetString("InformationNavslide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string MoreInfoDetails {
            get {
                return ResourceManager.GetString("MoreInfoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Magazine.
        /// </summary>
        public static string OnlineMagazineCol {
            get {
                return ResourceManager.GetString("OnlineMagazineCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Things To Do.
        /// </summary>
        public static string OtherThingstodoinfo {
            get {
                return ResourceManager.GetString("OtherThingstodoinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has returned 100 results..
        /// </summary>
        public static string pagiantionBox {
            get {
                return ResourceManager.GetString("pagiantionBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 People.
        /// </summary>
        public static string peoplecount {
            get {
                return ResourceManager.GetString("peoplecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string PoolInfo {
            get {
                return ResourceManager.GetString("PoolInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyCol {
            get {
                return ResourceManager.GetString("PrivacyPolicyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Propertiesinfo {
            get {
                return ResourceManager.GetString("Propertiesinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string PropertyLabel {
            get {
                return ResourceManager.GetString("PropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Units.
        /// </summary>
        public static string Rentalunitinfo {
            get {
                return ResourceManager.GetString("Rentalunitinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Unit.
        /// </summary>
        public static string RentalunitLabel {
            get {
                return ResourceManager.GetString("RentalunitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resort Admin.
        /// </summary>
        public static string ResortAdminCol {
            get {
                return ResourceManager.GetString("ResortAdminCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string RestaurantsInfo {
            get {
                return ResourceManager.GetString("RestaurantsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Images\card1.svg.
        /// </summary>
        public static string RowCard1 {
            get {
                return ResourceManager.GetString("RowCard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Beach.
        /// </summary>
        public static string SelectBeachCol {
            get {
                return ResourceManager.GetString("SelectBeachCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Beach.
        /// </summary>
        public static string SelectBeachname {
            get {
                return ResourceManager.GetString("SelectBeachname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        public static string SorByButton {
            get {
                return ResourceManager.GetString("SorByButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name(A-Z).
        /// </summary>
        public static string sortingBox {
            get {
                return ResourceManager.GetString("sortingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsConditionsCol {
            get {
                return ResourceManager.GetString("TermsConditionsCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gulf Shores Alabama Vacation Properties.
        /// </summary>
        public static string VacationpropHeading {
            get {
                return ResourceManager.GetString("VacationpropHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watersapce B618.
        /// </summary>
        public static string WaterspaceHeading {
            get {
                return ResourceManager.GetString("WaterspaceHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string WishlistName {
            get {
                return ResourceManager.GetString("WishlistName", resourceCulture);
            }
        }
    }
}
